/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ejemploPersistencia.vistas;

import javax.swing.JFrame;

/**
 *
 * @author Zeben
 */
public class EstasSeguro extends javax.swing.JDialog {

    /**
     * Creates new form EstasSeguro
     */
    public EstasSeguro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new java.awt.Color(204, 102, 255));  //color del background
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        botonSeguro = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(102, 102, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Has dado a acceder!!!!!\nQue sepas que si accedes es bajo tu\npropia responsabilidad, a mi no me \nvengas con historias después!!!!");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 65, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Vaya Chalao, hay que estar desesperado!!!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 27, 310, -1));

        botonSeguro.setBackground(new java.awt.Color(204, 51, 255));
        botonSeguro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonSeguro.setForeground(new java.awt.Color(0, 0, 0));
        botonSeguro.setText("Seguro!");
        botonSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguroActionPerformed(evt);
            }
        });
        getContentPane().add(botonSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 177, 140, 37));

        botonSalir.setBackground(new java.awt.Color(204, 51, 255));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        botonSalir.setText("Salir corriendo");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 177, 140, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/como_hacer_color_morado_49903_600_square.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguroActionPerformed
        // TODO add your handling code here:
        dispose();
        PantallaMenus menus = new PantallaMenus((JFrame) this.getParent(), true);
        menus.setVisible(true);
    }//GEN-LAST:event_botonSeguroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSeguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
