/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ejemploPersistencia.vistas;

import ejemploPersistencia.models.ControladorGralModelo;
import ejemploPersistencia.models.Usuario;
import javax.swing.JFrame;

/**
 *
 * @author Zeben
 */
public class PantallaInsertar extends javax.swing.JDialog {

    /**
     * Creates new form PantallaInsertar
     */
    public PantallaInsertar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textUser = new javax.swing.JTextField();
        textPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        botonReset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        botonSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserActionPerformed(evt);
            }
        });
        getContentPane().add(textUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 123, -1));
        getContentPane().add(textPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 123, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Introduce tu contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 109, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Introduce tu nombre de usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 65, 220, -1));

        botonCrear.setBackground(new java.awt.Color(204, 51, 255));
        botonCrear.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        botonCrear.setForeground(new java.awt.Color(0, 0, 0));
        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        getContentPane().add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        botonReset.setBackground(new java.awt.Color(204, 51, 255));
        botonReset.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        botonReset.setForeground(new java.awt.Color(0, 0, 0));
        botonReset.setText("Reset");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });
        getContentPane().add(botonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 51, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Introduce tu código");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 25, 140, -1));
        getContentPane().add(textCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 120, -1));

        botonSalir.setBackground(new java.awt.Color(204, 51, 255));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 3, 5)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 50, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/como_hacer_color_morado_49903_600_square.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUserActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        ControladorGralModelo registro = new ControladorGralModelo();
        Usuario usuario = new Usuario((textCodigo.getText()), textUser.getText(), textPass.getText());
        registro.crearUsuario(usuario);
        dispose();
        PantallaMenus menu = new PantallaMenus((JFrame)this.getParent(), true);
        menu.setVisible(true);
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
        PantallaMenus menu = new PantallaMenus((JFrame)this.getParent(), true);
        menu.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
        // TODO add your handling code here:
        textCodigo.setText("");
        textPass.setText("");
        textUser.setText("");
    }//GEN-LAST:event_botonResetActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonReset;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textPass;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
}
