/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ejemploPersistencia.vistas;

import javax.swing.JFrame;

/**
 *
 * @author Zeben
 */
public class PantallaMenus extends javax.swing.JDialog {

    /**
     * Creates new form PantallaMenus
     */
    public PantallaMenus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        crearUser = new javax.swing.JMenuItem();
        borrarUser = new javax.swing.JMenuItem();
        botonSalir = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/64962150-resplandecen-de-efectos-de-luz-de-neón-fuente-fuego-artificial-diseño-color-de-símbolos-de-texto-removebg-preview.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 190, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/como_hacer_color_morado_49903_600_square.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 358));

        jMenuBar1.setBackground(new java.awt.Color(204, 51, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        botonMenu.setText("Menú");

        jMenuItem1.setText("Blog");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        botonMenu.add(jMenuItem1);

        jMenuItem2.setText("Chatear");
        botonMenu.add(jMenuItem2);

        crearUser.setText("Crear Usuario");
        crearUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUserActionPerformed(evt);
            }
        });
        botonMenu.add(crearUser);

        borrarUser.setText("Borrar Usuario");
        borrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarUserActionPerformed(evt);
            }
        });
        botonMenu.add(borrarUser);

        jMenuBar1.add(botonMenu);

        botonSalir.setText("Salir");
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(botonSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUserActionPerformed
        // TODO add your handling code here:
        dispose();
        PantallaInsertar insertar = new PantallaInsertar((JFrame)this.getParent(), true);
        insertar.setVisible(true);
    }//GEN-LAST:event_crearUserActionPerformed

    private void borrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarUserActionPerformed
        // TODO add your handling code here:
        dispose();
        PantallaBorrar borrar = new PantallaBorrar((JFrame)this.getParent(), true);
        borrar.setVisible(true);
        
    }//GEN-LAST:event_borrarUserActionPerformed

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem borrarUser;
    private javax.swing.JMenu botonMenu;
    private javax.swing.JMenu botonSalir;
    private javax.swing.JMenuItem crearUser;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
