package ejemploPersistencia.vistas;

/**
 *
 * @author Zeben
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(380, 625);
        setLocation(600, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        botonSalir = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(89, 146, 183));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/64962150-resplandecen-de-efectos-de-luz-de-neón-fuente-fuego-artificial-diseño-color-de-símbolos-de-texto-removebg-preview.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 0, 190, 225);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Bienvenido a chatea con Zeben");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 220, 290, 25);

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(204, 102, 255));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        textArea.setForeground(new java.awt.Color(0, 0, 0));
        textArea.setRows(5);
        textArea.setText("Si eres informático y no tienes amigos,\nentonces eres como yo, un pringao.\nAsi que vente a chatear en esta \"red \nasocial\" y hablamos de todo y de nada.\nSeamos chateAmigos!!!!");
        textArea.setBorder(null);
        textArea.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(textArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 290, 275, 123);

        botonSalir.setBackground(new java.awt.Color(204, 51, 255));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 3, 8)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir);
        botonSalir.setBounds(290, 550, 70, 20);

        botonAceptar.setBackground(new java.awt.Color(204, 51, 255));
        botonAceptar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(0, 0, 0));
        botonAceptar.setText("Acceder");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar);
        botonAceptar.setBounds(120, 470, 105, 44);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/como_hacer_color_morado_49903_600_square.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 370, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        EstasSeguro seguro = new EstasSeguro(this, true);
        seguro.setVisible(true);
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
